pipeline:
  build:
    image: dennisfischer/llvm:6.0-json
    commands:
    - mkdir build/
    - cd build/
    - cmake ..
    - cmake --build . -- -j4
    when:
      branch: [ master, graph ]

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]
