pipeline:
    build:
        image: dennisfischer/llvm:6.0
        commands:
            - mkdir build/
            - cd build/
            - cmake ..
            - cmake --build . -- -j4
        when:
            branch: [ master, graph ]
